# Generated by Django 4.1.5 on 2023-02-03 17:29

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Gallery",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=64, verbose_name="Nazwa")),
                ("desc", models.CharField(max_length=1024, verbose_name="Opis")),
                (
                    "date",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="Czas wrzucenia",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=64, verbose_name="Nazwa")),
                ("desc", models.CharField(max_length=1024, verbose_name="Opis")),
                ("fs_file", models.ImageField(upload_to="")),
                (
                    "date",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="Czas wrzucenia",
                    ),
                ),
                (
                    "gallery",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="images_rel",
                        to="gallery.gallery",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ImageComment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("text", models.CharField(max_length=1024)),
                (
                    "date",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="Czas wrzucenia",
                    ),
                ),
                (
                    "image",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments_rel",
                        to="gallery.image",
                        verbose_name="Zdjęcie",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GalleryComment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("text", models.CharField(max_length=1024)),
                (
                    "date",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="Czas wrzucenia",
                    ),
                ),
                (
                    "gallery",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments_rel",
                        to="gallery.gallery",
                        verbose_name="Galeria",
                    ),
                ),
            ],
        ),
    ]
